import { useHome } from './logic'
import { ColorPicker, Main } from './styles'

import Head from 'next/head'

export const Home = () => {
  const { customTheme, onColorChange } = useHome()

  return (
    <>
      <Head>
        <title>Home</title>

        <link rel='icon' href='/favicon.ico' />

        <meta name='description' content='Generated by create next app' />
      </Head>

      <Main css={{ ...customTheme }}>
        <ColorPicker
          type='color'
          onChange={onColorChange}
          defaultValue={customTheme.bg}
          css={{ borderColor: customTheme.color }}
        />
        Test
      </Main>
    </>
  )
}
