import { useHome } from './logic'
import { Background } from './styles'

import { Header } from './Header'
import { Navbar } from './Navbar'
import { Projects } from './Projects'
import { Techs } from './Techs'

import { SmartFixedNav } from '@app/components/utilities/SmartFixedNav'
import Head from 'next/head'

export const Home = () => {
  const {
    techsRef,
    navItems,
    bgGradient,
    projectsRef,
    customTheme,
    onColorChange,
    onResetClick
  } = useHome()

  return (
    <>
      <Head>
        <title>Home</title>

        <link rel='icon' href='/favicon.ico' />

        <meta name='description' content='Generated by create next app' />
      </Head>

      <SmartFixedNav
        nav={<Navbar items={navItems} />}
        aboveContent={
          <Header
            customTheme={customTheme}
            onResetClick={onResetClick}
            onColorChange={onColorChange}
          />
        }
      />

      <Techs customTheme={customTheme} ref={techsRef} />

      <Projects ref={projectsRef} />

      <Background css={{ background: bgGradient }} />
    </>
  )
}
